<?php

/**
 * @file
 * Primary module hooks for Spreadspace cancel module.
 */

const SPREADSPACE_CANCEL_FILES_STATE = 'spreadspace_cancel_fids_state';

/**
 * Implements hook_mail().
 */
function spreadspace_cancel_mail($key, &$message, $params) {
  switch ($key) {

    // Email to customer requesting the cancel.
    case 'contract_cancel_customer':
      $config = \Drupal::config('spreadspace_cancel.settings');
      $site_config = \Drupal::config('system.site');
      $message['subject'] = 'Kündigungsbestätigung';
      $message['body'][] = $config->get('email_body');
      $message['body'][] = $site_config->get('name');
      break;

    // Email copy to client.
    case 'contract_cancel_client':
      $message['subject'] = "Kündigung Kundennummer {$params['customer_id']}";
      break;

  }
}

/**
 * Implements hook_cron().
 */
function spreadspace_cancel_cron() {
  $request_time = \Drupal::time()->getRequestTime();
  $previous = \Drupal::state()->get('spreadspace_cancel_file_cron', 0);
  $interval = 60 * 60 * 24;

  if ($previous < ($request_time - $interval)) {
    $fids = \Drupal::state()->get(SPREADSPACE_CANCEL_FILES_STATE, []);
    if (empty($fids)) {
      return;
    }

    // Check pdfs older than 24 hours and remove them.
    $file_storage = \Drupal::entityTypeManager()->getStorage('file');
    $files = $file_storage
      ->getQuery()
      ->condition('fid', $fids, 'IN')
      ->condition('created', $request_time - $interval, '<')
      ->execute();
    $file_storage->delete($file_storage->loadMultiple($files));

    \Drupal::state()->set(SPREADSPACE_CANCEL_FILES_STATE, array_diff($fids, $files));
    \Drupal::state()->set('spreadspace_cancel_file_cron', $request_time);
  }
}
